### ISSUE TITLE
First Line isn't Post-title

### ISSUE THREAD

**Issue by soehlschlaeger** [akirk/enable-mastodon-apps#22]
I had tested it in Mona. I'm using standard posts. 

Any ideas for debugging?

Wordpress Post Title created in WordPress are not showing in Mona too. 

Ps: great work!

**Comment by soehlschlaeger** [comment]
I see. It's a problem with Mona on IOS.

**Comment by akirk** [comment]
Could you describe the problem in a little more detail? Maybe with screenshots? Thanks!

**Comment by soehlschlaeger** [comment]
![image](https://user-images.githubusercontent.com/58472193/236638488-aeeb474a-33b4-437a-b701-65ff17ba56ae.png)

This is my composer... first line is my headline.

**Comment by soehlschlaeger** [comment]
![image](https://user-images.githubusercontent.com/58472193/236638538-07e43a62-ee81-4c15-a43b-2eea8a43d2b4.png)

So, it isn't in the headline on Wordpress.

**Comment by akirk** [comment]
I see, maybe we can handle this, though. Could you use the debug mode see (#23) and submit the post and then check the screen if you see a request `POST /api/v1/statuses` and what parameters it sends (please update to 0.3.6 before since I fixed a logging bug htere)? I just tried it locally with Mona and it worked fine. Please double check that the status for Mona is actually set to "standard".

<img width="1312" alt="Screenshot 2023-05-06 at 20 29 03" src="https://user-images.githubusercontent.com/203408/236641044-8e59a61d-71e0-4969-b093-8ab95516f366.png">

**Comment by soehlschlaeger** [comment]
> I see, maybe we can handle this, though. Could you use the debug mode see (#23) and submit the post and then check the screen if you see a request `POST /api/v1/statuses` and what parameters it sends (please update to 0.3.6 before since I fixed a logging bug htere)? I just tried it locally with Mona and it worked fine. Please double check that the status for Mona is actually set to "standard".
> 
> 
> 
> <img width="1312" alt="Screenshot 2023-05-06 at 20 29 03" src="https://user-images.githubusercontent.com/203408/236641044-8e59a61d-71e0-4969-b093-8ab95516f366.png">
> 
> 

"Please double check that the status for Mona is actually set to "standard""

This was it. Now this is fine. Thanks for the help. And, I have to say it one more time: GREAT JOB!
