### ISSUE TITLE
Migration to this account?

### ISSUE THREAD

**Issue by shaunrobinson** [akirk/enable-mastodon-apps#27]
If I set this up and have a working account from my WordPress blog, does migrating work to send existing followers to this account, as if it were another Mastodon account?

Thanks!

**Comment by akirk** [comment]
No, this plugin is just so that Mastodon apps can talk to your WordPress. If you want ActivityPub functionality you need to additionally use the Friends Plugin + ActivityPub plugin. Unfortunately migration has not yet been implemented (https://github.com/akirk/friends/issues/134 and https://github.com/Automattic/wordpress-activitypub/issues/178).
