### ISSUE TITLE
Critical Error on saving changes

### ISSUE THREAD

**Issue by knut-hildebrandt** [akirk/enable-mastodon-apps#5]
After installing the app I registered various apps - Fedilab, Pinafore, Tusky -  successfully and the toots of people the account follows are displayed in all of these. But that's it. I neither can post - toots and direct messages are not shown in the timelines of my followers - nor can I follow new people.  The ones I follow right now I added through the friends plugin. The apps also do not show how many people I follow or follow me and neither who they are.

Trying to find out if changes in the settings might alter this behavior I got during saving these changes an error message and an email describing the error. 

> Error-Details
==============
An Error of Typ E_ERROR occured at line 93 of the file /home/webpages/xxx/yyy/WordPress_01/wp-content/plugins/enable-mastodon-apps/includes/class-mastodon-app.php. Error message: Uncaught TypeError: Cannot access offset of type string on string in /home/webpages/xxx/yyy/WordPress_01/wp-content/plugins/enable-mastodon-apps/includes/class-mastodon-app.php:93
Stack trace:
#0 /home/webpages/xxx/yyy/WordPress_01/wp-content/plugins/enable-mastodon-apps/includes/class-mastodon-app/includes/class-mastodon-admin.php(166): Enable_Mastodon_Apps\Mastodon_App->set_post_formats(Array)
#1 /home/webpages/xxx/yyy/WordPress_01/wp-includes/class-wp-hook.php(308): Enable_Mastodon_Apps\Mastodon_Admin->process_admin('')
#2 /home/webpages/xxx/yyy/WordPress_01/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /home/webpages/xxx/yyy/WordPress_01/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /home/webpages/xxx/yyy/WordPress_01/wp-admin/admin.php(237): do_action('load-settings_p...')
#5 /home/webpages/xxx/yyy/WordPress_01/wp-admin/options-general.php(10): require_once('/home/webpages/...')
#6 {main}
  thrown

WordPress-Version 6.2
Plugin-Version: Enable Mastodon Apps (Version 0.1.1)
PHP-Version 8.1.17

**Comment by akirk** [comment]
Thank you for the report and sorry about that bug when saving settings. It'll be fixed in the next release. 

I am not yet sure why you cannot post or follow new people. Which client are you using?

When posting something, can you see it in your own wp-admin under posts? Or ar the posts not created at all?

Do you have access to your server's error log? Could you check if there was an error around that timestamp?

Thanks for your help!

**Comment by knut-hildebrandt** [comment]
Thanks for taking your time to look into that matter.

> I am not yet sure why you cannot post or follow new people. Which client are you using?
I'm using various clients. My favorite one is Fedilab on the Android phone. But I also tried Pinafore and Tusky. In none of these apps I can follow accounts. I can't even search for them. The two accounts I follow now I added through the friends plugin, which is enabled too, as well as ActivityPub plugin.

> When posting something, can you see it in your own wp-admin under posts? Or ar the posts not created at all?
I see them and I even see direct messages, which in the backend are marked "private" but never get through to the person who should get them. In fact I can't receive direct messages neither. If I go to the "Direct message" or the  "Notification" tab these are empty. In Pinafor it says "Nothing to show" and there is for a short time a  notification window saying "Internet request failed. Showing offline content."

> Do you have access to your server's error log? Could you check if there was an error around that timestamp?
Which log file are you asking for? Can connect through ssh and had a look at the servers php error-log. Nothing when I did a search for accounts in Fedilab and Pinafore.

**Comment by akirk** [comment]
>  I can't even search for them.

Indeed, searching for accounts is not yet implemented. But it should be possible to follow accounts that you discover through boosts of others. Did you try that?

> I see them and I even see direct messages, which in the backend are marked "private" but never get through to the person who should get them.

I don't believe I have implemented private messages properly yet. It certainly needs another iteration, probably working together with @pfefferle of https://github.com/pfefferle/wordpress-activitypub/ since they need careful handling on the sending side in ActivityPub.

> If I go to the "Direct message" or the "Notification" tab these are empty.

These endpoints are not yet implemented, that's why. I am not yet sure how to do the direct messages. For notifications, [Friends 2.5.0](https://github.com/akirk/friends/releases/tag/2.5.0) now has support for external mentions (i.e. of people who you don't follow), so I think I can implement something useful in the next release of the Enable Mastodon Apps plugin

> Which log file are you asking for? 

I meant to ask for the php error-log indeed.

In the [latest 0.2.0 release](https://github.com/akirk/enable-mastodon-apps/releases/tag/0.2.0) of a few minutes ago, I made some improvements to the outgoing mentions logic, I hope this will now work better. Please let me know and sorry for the trouble. It can be a bit hairy to merge the architecture of Mastodon with WordPress's, so some things need tinkering until the approach works well in practice!

**Comment by knut-hildebrandt** [comment]
Great that the new version is out. Just installed it and run some tests. And don't worry about "the trouble". Even though it's free software users should support the developers in some way. My way is trying to help improve the software ;-)

> Indeed, searching for accounts is not yet implemented. But it should be possible to follow accounts that you discover through boosts of others. Did you try that?

Yes, that works. Once I get to the profile page by clicking it's avatar I can follow it without problem.

> In the [latest 0.2.0 release](https://github.com/akirk/enable-mastodon-apps/releases/tag/0.2.0) of a few minutes ago, I made some improvements to the outgoing mentions logic, I hope this will now work better.

It worked perfectly with Pinafore and Fedilab. Thanks for fixing.

There is one more thing I noticed. Looking at my own profile page I don't get the correct data displayed. Actually the data displayed differs with the account I come from. If I go to the page from my own (WP) account, both follows and followers are said to be zero, which not is true. Clicking the respective tabs causes an error. Pinafore is more specific with the error message and says:  Error: Request failed: 404. Do I go the profile from another account on another server the number of Follower is always shown correctly, the number of accounts I follow is always show to be zero. Only exception, when I go to the profile from the account I follow back.

BTW, shall I open a new issue for everything I encounter?

Thanks again for the Plugin. I hope it soon will be able to provide all basic Mastodon features.
